### ISSUE TITLE
installation through the Package Manager

### ISSUE THREAD

**Issue by emmanueljourdan** [arshiacont/antescofo-sublime-package#1]
It would be cool to install it with the [Package Manager](https://packagecontrol.io).

Explanations are [there](https://packagecontrol.io/docs/submitting_a_package).

**Comment by arshiacont** [comment]
That’s the plan.. I’m waiting for some people to test first…

**Comment by arshiacont** [comment]
Done and pending:
https://github.com/wbond/package_control_channel/pull/5134
Thanks... .

**Comment by arshiacont** [comment]
Done: https://github.com/wbond/package_control_channel/pull/5134
