### ISSUE TITLE
Labels with spaces confuse syntax coloring

### ISSUE THREAD

**Issue by kymbalon** [arshiacont/antescofo-sublime-package#8]
After a label like e.g.
`NOTE 6900 1/4 "1q before K"`
the only color is red, i.e. all text (everything) appears in just one color.

Maybe it's a problem in the color scheme, or a problem of Sublime Text 3.

**Comment by slemouton** [comment]
I think I have corrected this, 
pull request sent to arshia : watch out !

**Comment by arshiacont** [comment]
@kymbalon : Just merged.. Could you please test and let us know if it's fine?

**Comment by kymbalon** [comment]
It's fixed: It looks fine now.
